###Local application properties

server:
  port: 8761
  application :
    name : SERVICE-DISCOVERY

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultUrl: localhost:8761/eureka/
---