#DEv peer 1

spring:
  application:
    name: EUREKA-SERVER-DEV-PEER1

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

server:
  port: 8762

---
